services:
  {{AGENT_CONTAINER_NAME}}:
    build: .
    container_name: {{AGENT_CONTAINER_NAME}}
    environment:
      - OPENAI_API_KEY=your-openai-api-key-here
      # Add your custom environment variables here
    stdin_open: true
    ports:
      - "5000"
    tty: true
    networks:
      - agents-net

networks:
  agents-net:
    external: true